language: java
jdk: openjdk8
script: "mvn clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -U"
branches:
  only:
  - master
cache:
  directories:
  - '$HOME/.m2/repository'
notifications:
  email:
  - luokaiqiongmou@foxmail.com